### ISSUE TITLE
[FEATURE] Update the EAP Testing API for Release 2

### ISSUE THREAD

**Issue by glennb-mitre** [Wireless-Innovation-Forum/Spectrum-Access_System-Release-2#1]
### Description
Update the Release 1 "API" to support Release 2 test cases. 

### Problem Statement
Rel 2 enhanced antenna pattern is not implemented. We need to implement it using rel 1 antenna.py file as reference.

### Requirements
Annex 5.2.1 of referenced TS-1001.
- Table 2. Necessity of enhanced antenna pattern information in each method, implement:
    - B1, C, D, E
    - Method F is implemented in referenced R1 API (antenna.py)
- Algorithm definitions provided.

### Files
- TS-1001 v1.4.1-r5.0 (towards 1.5.0)
- [antenna.py](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/tree/master/src/harness/reference_models/antenna)

### Tasks
Include specific tasks in the order they need to be done in.
- [ ] Review Method F in Antenna.py
- [ ] Develop test case for Method F
- [ ] Develop test cases for Methods B1, C, D, E
- [ ] Implement method B1, C, D, E
